### PR TITLE
Master

### PR DESCRIPTION
**Pull request by tonymobster**
For settings that are constant across environments having to create
multiple entries for each environment gets cumbersome. This adds a
retrieval strategy which ignores the environment when no matching key is
found on the first go. 
E.g. <add key="CommonSetting" value="Common value across all environments"/> instead of:
<add key="Dev.CommonSetting" value="Common value across all environments"/>
<add key="QA.CommonSetting" value="Common value across all environments"/>

### CODE REVIEW

**Comment by eaardal** [comment]
Hi
Thanks for fixing this. The original thought was to just use System.Configuration.ConfigurationManager for getting the non-environment specific stuff, but why not have Konfiggy handle those too. Much appreciated.

**Comment by tonymobster** [comment]
Yeah that was what I was doing too, but decided a single consistent API for interacting with settings was preferable, especially since it was so simple to implement. Great library btw!

**Comment by tonymobster** [comment]
Any chance of getting this pushed to nuget? Wanna update my package for an app I'm building. I hate committing references into my repos.

**Comment by eaardal** [comment]
Yeah i'll push it to nuget today after work or tomorrow morning.

**Pull request merged**
